#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx
- name: Ensure Nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy index.html to Nginx web root with correct permissions
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Ensure Nginx service is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
